name: Sync Fork with Upstream

on:
  schedule:
    # Run every day at 6:00 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Configure Git
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Add upstream remote
      run: |
        git remote add upstream https://github.com/debridmediamanager/hashlists.git || true
        git fetch upstream
    
    - name: Sync main branch
      run: |
        git checkout main || git checkout master
        git merge upstream/main || git merge upstream/master
    
    - name: Push changes
      run: |
        git push origin main || git push origin master
